version: '3.8'  # Specify the docker-compose version

services:
  postgres:
    image: postgres:latest
    container_name: echo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data using a named volume

volumes:
  postgres_data:
